# Run LLM recommendation
name: Daily RSS Recommendation

# Controls when the workflow will run
on:
  schedule:
    - cron: "30 0 * * *"   # 12:30 AM UTC
  workflow_dispatch:

# By default regress against accel-sim's dev branch
env:
  SECRET_GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
  SECRET_MAIL_USERNAME: ${{ secrets.SECRET_MAIL_USERNAME }}
  SECRET_MAIL_PASSWORD: ${{ secrets.SECRET_MAIL_PASSWORD }}
  MODEL_NAME: ${{ vars.MODEL_NAME }}
  KEYWORDS: ${{ vars.KEYWORDS }}
  STRONG_KEYWORDS: ${{ vars.STRONG_KEYWORDS }}
  SYSTEM_MESSAGE_START: ${{ vars.SYSTEM_MESSAGE_START }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  llm-recommendation:
    runs-on: ubuntu-latest
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Dump RSS links to file
        run: echo ${{ vars.FEED_LINKS }} | tr ',' '\n' | tee feeds.txt
      - name: Run recommendation
        run: FEEDS_FILE=./feeds.txt python3 $GITHUB_WORKSPACE/main.py
      - name: Prepare email
        run: |
          DATENOW=$(date +'%Y-%m-%dT%H:%M:%S')
          [ -e email.html ] && echo "EMAIL_FILE=file://email.html" >> $GITHUB_ENV
          [ ! -e email.html ] && echo "EMAIL_SUBJECT=RSSFeedBot no recommendations $DATENOW " >> $GITHUB_ENV
          [ -e email.html ] && echo "EMAIL_SUBJECT=RSSFeedBot new recommendations $DATENOW " >> $GITHUB_ENV
          echo "Done"
      - name: Send email
        uses: dawidd6/action-send-mail@v4
        with:
          # Required mail server address if not connection_url:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended) mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: ${{ env.EMAIL_SUBJECT }}
          # Required recipients' addresses:
          to: ${{ secrets.MAIL_RECIPIENTS }}
          # Required sender full name (address can be skipped):
          from: RSSFeedBot # <user@example.com>
          # Optional HTML body read from file:
          html_body: ${{ env.EMAIL_FILE }}
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: false
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: normal
          # Optional nodemailerlog: true/false
          nodemailerlog: true
          # Optional nodemailerdebug: true/false if true lognodem will also be set true
          nodemailerdebug: true
