# Run LLM recommendation
name: Daily RSS Recommendation

# Controls when the workflow will run
on:
  schedule:
    - cron: "30 0 * * *"   # 12:30 AM UTC
  workflow_dispatch:

# By default regress against accel-sim's dev branch
env:
  SECRET_GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
  SECRET_MAIL_USERNAME: ${{ secrets.SECRET_MAIL_USERNAME }}
  SECRET_MAIL_PASSWORD: ${{ secrets.SECRET_MAIL_PASSWORD }}
  MODEL_NAME: ${{ vars.MODEL_NAME }}
  KEYWORDS: ${{ vars.KEYWORDS }}
  STRONG_KEYWORDS: ${{ vars.STRONG_KEYWORDS }}
  SYSTEM_MESSAGE_START: ${{ vars.SYSTEM_MESSAGE_START }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  llm-recommendation:
    runs-on: ubuntu-latest
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Dump RSS links to file
        run: echo ${{ vars.FEED_LINKS }} | tr ',' '\n' | tee feeds.txt
      - name: Run recommendation
        run: FEED_FILE=./feeds.txt python3 $GITHUB_WORKSPACE/main.py
